### ISSUE TITLE
Docker compose issues

### ISSUE THREAD

**Issue by Janik313** [byceps/byceps#12]
Hey im kinda stuck on running byceps with compose.

Im getting this issue if i try to run any command

`root@docker:/home/janik/docker/byceps# docker compose run --rm byceps-admin byceps generate-secret-key > ./secret_key.txt
[+] Creating 2/0
 ✔ Container byceps-db-1     Running0.0s
 ✔ Container byceps-redis-1  Running0.0s
Traceback (most recent call last):
  File "/home/byceps/.local/bin/byceps", line 5, in <module>
    from byceps.cli.cli import cli
ModuleNotFoundError: No module named 'byceps.cli'
root@docker:/home/janik/docker/byceps#`

**Comment by homeworkprod** [comment]
Hey @Janik313, thanks for trying out BYCEPS!

I was unable to reproduce the error by following the documentation for the Docker Compose-based installation.

Can you tell me more about the environment you're running this in, and which commit (`git rev-parse HEAD`) of BYCEPS you're on? Did you change something along the way? And ideally describe exactly how to reproduce the error?

**Comment by Janik313** [comment]
Hey, I just tried again and this time everything just worked. So i guess that i just got unlucky, but thanks for your help

**Comment by homeworkprod** [comment]
Luck shouldn't be involved in this, but I'm glad you got it working anyway. :)
