### ISSUE TITLE
Difference between doc and repo regarding apps.toml

### ISSUE THREAD

**Issue by Darkwinder** [byceps/byceps#21]
Hi there,
I followed 

https://byceps.readthedocs.io/en/latest/installation_docker/index.html

until I came to the point

cp config/apps_example.toml config/apps.toml

But there is an empty folder

config/apps.toml/

already existing, and therefore the copy command can not copy this file.
The folder config/apps.toml/ was probably created between the checkout and the creation of the initial user, as it is owned by root, not the user I checked out with. 
So following the steps of the install doc I am unable to install without fixing this bug manually. 

So obviously some step described in the install doc  created a folder apps.toml instead of a file apps.toml below config.
But according to the copy command there should be either no folder apps.toml nor a file apps.toml at this point, as both would let the copy command fail.

regards

Dirk

**Comment by homeworkprod** [comment]
Thanks again for the report.

In faa3c79 I have moved the section of the documentation that describes the creation of the applications configuration file before the section with the first run of Docker. This should prevent Docker from creating a directory with the name of that configuration file.
