### ISSUE TITLE
Running without docker?

### ISSUE THREAD

**Issue by Pimmal** [byceps/byceps#22]
Can this system be installed on a webspace without using docker container?

**Comment by homeworkprod** [comment]
BYCEPS can be installed and run without Docker (see section [Installation (native)](https://byceps.readthedocs.io/en/latest/installation/index.html) in the docs).

It does, however, require [certain software](https://byceps.readthedocs.io/en/latest/installation/requirements.html) to be available as well as SSH access which aren't usually available (or sufficiently configurable) on "classic" webspace which is public storage space, PHP, and MySQL with just FTP-ish access.
