### ISSUE TITLE
Impossible to delete a user from admin panel

### ISSUE THREAD

**Issue by tech62** [byceps/byceps#7]
![image](https://user-images.githubusercontent.com/16237642/135710395-7520d983-fc16-4de2-921f-9a5eefe5924f.png)

Fix : 
Change 'delete account' in this line to 'delete user'
https://github.com/byceps/byceps/blob/c2b42e729461562e27bce3304fa184c43d6d9399/byceps/blueprints/admin/user/forms.py#L105

Or change the instruction on the form (by changing "delete user" to "delete account")
https://github.com/byceps/byceps/blob/c2b42e729461562e27bce3304fa184c43d6d9399/byceps/blueprints/admin/user/templates/admin/user/delete_account_form.html#L18

**Comment by homeworkprod** [comment]
Good catch, thanks for the report!

This is a bug in the English translation. 77b910ae30c3026c4c6930105d7bc72cfec2cacf (and the subsequent translation catalog recompilation commit) fixes this.
